app:
  name: canary-app

stable:
  enabled: true
  version: v1
  replicas: 2
  imageTag: 71756bc6bbb113b35c520355d51242d7d4e73fb4

canary:
  enabled: true
  version: v2
  replicas: 1
  imageTag: 71756bc6bbb113b35c520355d51242d7d4e73fb4

image:
  repository: caominhquang1604/canary-app

service:
  type: NodePort
  port: 80
  targetPort: 5000
