name: CI - Build Image & Update Helm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Login Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASS }}" | docker login \
          -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build & Push Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t caominhquang1604/canary-app:$IMAGE_TAG ./app
        docker push caominhquang1604/canary-app:$IMAGE_TAG

    - name: Update Helm values.yaml (CANARY ONLY)
      run: |
        IMAGE_TAG=${{ github.sha }}
        sed -i "s/^  imageTag:.*/  imageTag: $IMAGE_TAG/" canary-chart/values.yaml

    - name: Commit & push Helm changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add canary-chart/values.yaml
        git commit -m "ci: update canary image to ${{ github.sha }}"
        git push
